package main

const (
	totalQuizzes            = 2  // Constant for total number of quizzes
	numberOfQuestions       = 50 // Constant for total number of questions
	numberOfQuestionOptions = 4  // Constant for number of options for each question
)

var capitals = map[string]string{
	"Afghanistan":                      "Kabul",
	"Albania":                          "Tirana",
	"Algeria":                          "Algiers",
	"American Samoa":                   "Pago Pago",
	"Andorra":                          "Andorra la Vella",
	"Angola":                           "Luanda",
	"Anguilla":                         "The Valley",
	"Antigua and Barbuda":              "Saint John's",
	"Argentina":                        "Buenos Aires",
	"Armenia":                          "Yerevan",
	"Aruba":                            "Oranjestad",
	"Australia":                        "Canberra",
	"Austria":                          "Vienna",
	"Azerbaijan":                       "Baku",
	"The Bahamas":                      "Nassau",
	"Bahrain":                          "Manama",
	"Bangladesh":                       "Dhaka",
	"Barbados":                         "Bridgetown",
	"Belarus":                          "Minsk",
	"Belgium":                          "Brussels",
	"Belize":                           "Belmopan",
	"Benin":                            "Porto-Novo",
	"Bermuda":                          "Hamilton",
	"Bhutan":                           "Thimphu",
	"Bolivia":                          "La Paz",
	"Bonaire":                          "Kralendijk",
	"Bosnia and Herzegovina":           "Sarajevo",
	"Botswana":                         "Gaborone",
	"Brazil":                           "Brasília",
	"British Virgin Islands":           "Road Town",
	"Brunei":                           "Bandar Seri Begawan",
	"Bulgaria":                         "Sofia",
	"Burkina Faso":                     "Ouagadougou",
	"Burundi":                          "Gitega",
	"Cambodia":                         "Phnom Penh",
	"Cameroon":                         "Yaoundé",
	"Canada":                           "Ottawa",
	"Cape Verde":                       "Praia",
	"Cayman Islands":                   "George Town",
	"Central African Republic":         "Bangui",
	"Chad":                             "N'Djamena",
	"Chile":                            "Santiago",
	"China":                            "Beijing",
	"Christmas Island":                 "Flying Fish Cove",
	"Cocos Islands":                    "West Island",
	"Colombia":                         "Bogotá",
	"Comoros":                          "Moroni",
	"Republic of the Congo":            "Brazzaville",
	"Democratic Republic of the Congo": "Kinshasa",
	"Cook Islands":                     "Avarua",
	"Costa Rica":                       "San José",
	"Côte d'Ivoire":                    "Yamoussoukro",
	"Croatia":                          "Zagreb",
	"Cuba":                             "Havana",
	"Curaçao":                          "Willemstad",
	"Cyprus":                           "Nicosia",
	"Czech Republic":                   "Prague",
	"Denmark":                          "Copenhagen",
	"Djibouti":                         "Djibouti",
	"Dominica":                         "Roseau",
	"Dominican Republic":               "Santo Domingo",
	"East Timor":                       "Díli",
	"Ecuador":                          "Quito",
	"Egypt":                            "Cairo",
	"El Salvador":                      "San Salvador",
	"Equatorial Guinea":                "Malabo",
	"Eritrea":                          "Asmara",
	"Estonia":                          "Tallinn",
	"Eswatini":                         "Mbabane",
	"Ethiopia":                         "Addis Ababa",
	"Falkland Islands":                 "Stanley",
	"Faroe Islands":                    "Tórshavn",
	"Fiji":                             "Suva",
	"Finland":                          "Helsinki",
	"France":                           "Paris",
	"French Guiana":                    "Cayenne",
	"French Polynesia":                 "Papeete",
	"Gabon":                            "Libreville",
	"The Gambia":                       "Banjul",
	"Georgia":                          "Tbilisi",
	"Germany":                          "Berlin",
	"Ghana":                            "Accra",
	"Gibraltar":                        "Gibraltar",
	"Greece":                           "Athens",
	"Greenland":                        "Nuuk",
	"Grenada":                          "St. George's",
	"Guadeloupe":                       "Basse-Terre",
	"Guam":                             "Hagåtña",
	"Guatemala":                        "Guatemala City",
	"Guernsey":                         "Saint Peter Port",
	"Guinea":                           "Conakry",
	"Guinea-Bissau":                    "Bissau",
	"Guyana":                           "Georgetown",
	"Haiti":                            "Port-au-Prince",
	"Honduras":                         "Tegucigalpa",
	"Hong Kong":                        "Hong Kong",
	"Hungary":                          "Budapest",
	"Iceland":                          "Reykjavík",
	"India":                            "New Delhi",
	"Indonesia":                        "Jakarta",
	"Iran":                             "Tehran",
	"Iraq":                             "Baghdad",
	"Ireland":                          "Dublin",
	"Isle of Man":                      "Douglas",
	"Israel":                           "Jerusalem",
	"Italy":                            "Rome",
	"Jamaica":                          "Kingston",
	"Japan":                            "Tokyo",
	"Jersey":                           "St. Helier",
	"Jordan":                           "Amman",
	"Kazakhstan":                       "Astana",
	"Kenya":                            "Nairobi",
	"Kiribati":                         "Tarawa",
	"North Korea":                      "Pyongyang",
	"South Korea":                      "Seoul",
	"Kosovo":                           "Pristina",
	"Kuwait":                           "Kuwait City",
	"Kyrgyzstan":                       "Bishkek",
}
